# Authentication types
[auth]

[auth.cors]

use = "cors"
# Allow CORS from any host
origins = "*"

[auth.basic]

use = "basic"
user = "username"
password = "12345678"

[auth.bearer]

use = "bearer"
token = "12345"

[groups]

# Default group is using when service group is not defined
default = "private"

# Group with public access allow not authenticated users.
[groups.public]

# Authentication order
order = "cors,bearer"
authOnly = false

# Group with public access denied not authenticated users.
[groups.private]

order = "bearer"
authOnly = true
